# filepath: playbook/roles/docker_exporter/tasks/main.yml
---
- name: Ensure snapd package is installed
  ansible.builtin.package:
    name: snapd
    state: present
  become: true
  register: snapd_install_result

- name: Ensure snapd socket is enabled and started
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: true
    state: started
  become: true

- name: Refresh snapd
  community.general.snap:
    name:
      - snapd
    state: present
  become: true

- name: Install Docker snap package
  community.general.snap:
    name:
      - docker
    state: present
  become: true

- name: Install multiple packages from list
  vars:
    pipx_packages:
      - docker
      - requests
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    install_deps: true
  with_items: "{{ pipx_packages }}"

- name: Build the Docker image from the Dockerfile
  community.docker.docker_image:
    name: "{{ docker_image_name }}:{{ docker_image_tag }}"
    build:
      path: "{{ docker_build_context_path }}"
    source: build
    state: present
  become: true
  register: image_build_result

- name: Run the host metrics exporter container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    state: started
    restart_policy: "{{ container_restart_policy }}"
    ports:
      - "{{ host_port }}:{{ container_port }}"
  become: true
  register: container_run_result
